### ISSUE TITLE
Validation error on password field

### ISSUE THREAD

**Issue by frhbusra** [ariessa-deriv/syntrade-frontend#49]
**Describe the bug**
The password field gives an error even though the password follows the password requirements. Refer the screenshot below.

**To Reproduce**
1. Go to http://localhost:3000/signup
2. Enter a valid email
3. Enter a valid password
4. See the error

**Expected behavior**
The password should be validated as a correct password

**Screenshots**

![image](https://user-images.githubusercontent.com/108638778/204441274-fc6e127e-cb54-421a-8a0d-f65f1944f2fa.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser:Google Chrome
 - Version: 105

**Comment by ariessa-deriv** [comment]
Fixed in this [commit](https://github.com/ariessa-deriv/syntrade-frontend/commit/7b569cccb9a38da6c5da169f57147c0f5ab7ee39).
