### ISSUE TITLE
Create reset balance pop up

### ISSUE THREAD

**Issue by frhbusra** [ariessa-deriv/syntrade-frontend#66]
**Describe the bug**
No pop up message opens when choosing the Reset balance option in the navigation bar drop-down menu

**To Reproduce**
1. Go to http://localhost:3000/
2. Click the user icon at the top right corner of the page

![image](https://user-images.githubusercontent.com/108638778/205353468-e0fbffc2-a075-41cd-8981-805d84653b10.png)
3. Choose Reset balance option
4. See issue

**Expected behavior**
A pop up message should open to tell the user that their account balance has been successfully reset. The pop up message design is as below.

**Screenshots**

**FIgma**
![image](https://user-images.githubusercontent.com/108638778/205353281-35ffbf77-44ee-42cd-a1d4-d1459a5b801d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser:Google Chrome
 - Version: 105

**Comment by ariessa-deriv** [comment]
Already fixed in previous commits.
